activity:
  key: ''
  name: ''
registration_zone:
  member_data:
    capid: ''
    grade: ''
    membership_expiration: ''
    age_at_start: ''
    age_at_end: ''
  unit:
    region: ''
    wing: ''
    unit_number: ''
    unit_cc: ''
    unit_cc_email: ''
    wing_cc: ''
    wing_cc_email: ''
    unit_approved: ''
    unit_approved_date: ''
    wing_approved: ''
    wing_approved_date: ''
  eservices_contact_info:
    email: ''
    mailing_address:
      addr1: ''
      addr2: ''
      city: ''
      state: ''
      zip: ''
    cadet_parent:
      primary_phone: ''
      primary_email: ''
      emergency_phone: ''
      emergency_email: ''
  training:
    last_encampment: ''
    highest_oride: ''
    agh: ''
    wing_runner: ''
    ormb: ''
    ormi: ''
    cppt_expiration: ''
    icut: ''
    is100: ''
    is700: ''
    capt116: ''
    capt117_1: ''
    capt117_2: ''
    capt117_3: ''
    first_aid: ''
    meets_prereqs: ''
application_package:
  personal_info:
    capid: ''
    last_name: ''
    first_name: ''
    member_type: ''
    grade_in_school: ''
    gender: ''
    religious_preference: ''
    date_of_birth: ''
    shirt_size: ''
    height: ''
    weight: ''
    hair_color: ''
    eye_color: ''
  contact_info:
    primary_phone_number: ''
    secondary_phone_number: ''
    email_address: ''
  inbound_flight:
    arrival_date: ''
    arrival_time: ''
    airline: ''
    flight_number: ''
  outbound_flight:
    arrival_date: ''
    arrival_time: ''
    airline: ''
    flight_number: ''
  cadre_application:
    classes_to_teach: ''
    preferred_roles_senior:
      first: ''
      second: ''
      third: ''
      fourth: ''
      fifth: ''
    preferred_roles_cadet:
      first: ''
      second: ''
      third: ''
      fourth: ''
      fifth: ''
    resume:
      squadron_roles: ''
      encampments_attended: ''
      cadre_roles: ''
  health_history:
    food_allergies: ''
    other_allergies: ''
    medical_conditions: ''
    medical_condition_details: ''
    vaccines:
      tetanus: ''
      hepatitis: ''
      pneumonia: ''
      varicella_vax: ''
      varicella_date: ''
      influenza: ''
      covid19: ''
    medications: ''
    cadet_otcs:
      otc_blacklist: ''
      otc_reactions: ''
  emergency_contacts:
    primary_contact:
      name: ''
      relationship: ''
      phone_number: ''
    secondary_contact:
      name: ''
      relationship: ''
      phone_number: ''
  insurance:
    medical_insurance:
      company: ''
      policy_number: ''
      group_number: ''
      copay: ''
    prescription_insurance:
      company: ''
      policy_number: ''
      group_number: ''
      copay: ''
    family_physician:
      name: ''
      phone_number: ''
      mailing_address: ''
  signature: ''
payment:
  card_info:
    last_4: ''
    name_on_card: ''
    expiration: ''
  payment_info:
    transaction_id: ''
    transaction_date: ''
    successful_transaction: ''
    settled_status: ''
    settled_amount: ''
    credit_void: ''
    credit_amount: ''
  attendee_info:
    full_name: ''
    capid: ''
    multiple_attendees: ''
